# Generated by Django 2.2.2 on 2019-07-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offering_state',
            field=models.FloatField(default=0),
        ),
    ]
